### PR TITLE
:sparkles: redirect to homepage after exit call

### PR DESCRIPTION
**Pull request by ntchou**
https://github.com/Instant-Visio/InstantVisio-WebApp/issues/213

### CODE REVIEW

**Comment by ntchou** [comment]
captured (2) (1)

**Comment by MattiaPrimavera** [comment]
As discussed with @ntchou this should not be merged for the moment, since it won't affect the `RN` app in the expected way

**Comment by Abibibi** [comment]
> As discussed with @ntchou this should not be merged for the moment, since it won't affect the `RN` app in the expected way

ok, converting the PR to draft then

**Comment by MattiaPrimavera** [comment]
If you agree @ntchou, I think we can close this PR, as your commit was already included in `master` branch by [this commit](https://github.com/Instant-Visio/InstantVisio-WebApp/commit/32187c10a7755429ae09318bd34782534338e78a): I had to cherry-pick it for transitioning from RN to ionic.

**Comment by MattiaPrimavera** [comment]
You may also want to add the `fix` keyword to automatically close the linked issue.

**Comment by ntchou** [comment]
> If you agree @ntchou, I think we can close this PR, as your commit was already included in `master` branch by [this commit](https://github.com/Instant-Visio/InstantVisio-WebApp/commit/32187c10a7755429ae09318bd34782534338e78a): I had to cherry-pick it for transitioning from RN to ionic.

:+1:

**Pull request closed without merging**
